"""
Абстрактный базовый класс для всех писателей VTK файлов.
Определяет интерфейс для записи сеток в различные форматы.
"""
from abc import ABC, abstractmethod
from pathlib import Path
from ..core.base_grid import BaseGrid


class BaseVTKWriter(ABC):
    """
    Абстрактный базовый класс для записи VTK файлов.
    
    Атрибуты:
        grid: Сетка для записи
        file_format: Формат файла (например, 'ASCII', 'BINARY')
    """
    
    def __init__(self, grid: BaseGrid, file_format: str = "ASCII"):
        """
        Инициализация писателя VTK.
        
        Args:
            grid: Объект сетки для записи
            file_format: Формат файла
        """
        if not isinstance(grid, BaseGrid):
            raise TypeError(f"grid должен быть экземпляром BaseGrid, получен {type(grid)}")
        
        self.grid = grid
        self.file_format = file_format
    
    @abstractmethod
    def write(self, filepath: str) -> None:
        """
        Записывает сетку в VTK файл.
        
        Args:
            filepath: Путь к файлу для записи
            
        Raises:
            IOError: Если возникла ошибка при записи файла
        """
        pass
    
    def _get_header(self) -> str:
        """
        Возвращает заголовок для VTK файла.
        
        Returns:
            Строка заголовка
        """
        return f"VTK file generated by VTK Generator (grid: {self.grid.name})"
    
    def _validate_filepath(self, filepath: str) -> Path:
        """
        Валидирует и возвращает объект Path.
        
        Args:
            filepath: Путь к файлу
            
        Returns:
            Объект Path
            
        Raises:
            ValueError: Если путь некорректен
        """
        path = Path(filepath)
        
        # Создаем директорию если она не существует
        path.parent.mkdir(parents=True, exist_ok=True)
        
        return path
    
    def __repr__(self) -> str:
        """Строковое представление писателя."""
        return f"{self.__class__.__name__}(format='{self.file_format}', grid={self.grid.name})"