"""
Абстрактный базовый класс для писателей VTK файлов.
Определяет интерфейс для записи сеток в различные форматы.
"""
from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..core.base_grid import BaseGrid


class BaseVTKWriter(ABC):
    """
    Абстрактный базовый класс для всех писателей VTK файлов.
    
    Атрибуты:
        grid: Сетка для записи
        file_format: Формат файла (ASCII или BINARY)
    """
    
    def __init__(self, grid: 'BaseGrid', file_format: str = "ASCII"):
        """
        Инициализация базового писателя.
        
        Args:
            grid: Сетка для записи
            file_format: Формат файла (ASCII или BINARY)
        """
        self.grid = grid
        self.file_format = file_format
    
    @abstractmethod
    def write(self, filepath: str) -> None:
        """
        Записывает сетку в файл.
        
        Args:
            filepath: Путь к файлу для записи
        """
        pass
    
    def _validate_filepath(self, filepath: str) -> Path:
        """
        Валидирует и возвращает путь к файлу.
        
        Args:
            filepath: Путь к файлу для проверки
            
        Returns:
            Path объект пути к файлу
            
        Raises:
            ValueError: Если путь некорректен
        """
        path = Path(filepath)
        
        # Создаем директорию если она не существует
        if path.parent and not path.parent.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
        
        return path
    
    def _get_header(self) -> str:
        """
        Возвращает заголовок для VTK файла.
        
        Returns:
            Строка заголовка
        """
        return f"VTK file generated by VTK Generator (grid: {self.grid.name})"
