"""
Абстрактный базовый класс для писателей VTK файлов.
Определяет интерфейс, который должны реализовать все писатели.
"""
from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.base_grid import BaseGrid


class BaseVTKWriter(ABC):
    """
    Абстрактный базовый класс для всех писателей VTK.
    
    Атрибуты:
        grid: Объект сетки для записи
        file_format: Формат файла (ASCII или BINARY)
    """
    
    def __init__(self, grid: 'BaseGrid', file_format: str = "ASCII"):
        """
        Инициализация писателя.
        
        Args:
            grid: Объект сетки для записи
            file_format: Формат файла (ASCII или BINARY)
        """
        self.grid = grid
        self.file_format = file_format
    
    @abstractmethod
    def write(self, filepath: str) -> None:
        """
        Записывает сетку в файл.
        
        Args:
            filepath: Путь к файлу для записи
            
        Raises:
            IOError: Если возникла ошибка при записи
        """
        pass
    
    def _validate_filepath(self, filepath: str) -> Path:
        """
        Валидирует и возвращает путь к файлу.
        
        Создает родительскую директорию, если она не существует.
        
        Args:
            filepath: Путь к файлу
            
        Returns:
            Path объект пути
        """
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        return path
    
    def _get_header(self) -> str:
        """
        Возвращает заголовок для VTK файла.
        
        Returns:
            Строка заголовка (максимум 256 символов)
        """
        return f"VTK file generated by VTK Generator (grid: {self.grid.name})"
