"""Реализация Legacy ASCII VTK формата."""

from pathlib import Path
from typing import TextIO
from .base_writer import BaseVTKWriter


class LegacyASCIIVTKWriter(BaseVTKWriter):
    """Записывает сетку в VTK Legacy ASCII формате.
    
    Создает файлы в формате VTK 2.0 с типом DATASET STRUCTURED_POINTS.
    Этот формат совместим с большинством инструментов визуализации,
    включая ParaView и VisIt.
    """
    
    def write(self, filepath: str) -> None:
        """Записывает сетку в VTK файл.
        
        Args:
            filepath: Путь к выходному файлу (.vtk)
        """
        path = self._ensure_directory(filepath)
        
        with open(path, 'w') as f:
            self._write_header(f)
            self._write_dataset(f)
        
        print(f"VTK файл успешно записан: {path}")
    
    def _write_header(self, f: TextIO) -> None:
        """Записывает заголовок VTK файла.
        
        Args:
            f: Файловый объект для записи
        """
        f.write("# vtk DataFile Version 2.0\n")
        f.write(f"VTK file generated by VTK Generator (grid: {self.grid.name})\n")
        f.write("ASCII\n")
    
    def _write_dataset(self, f: TextIO) -> None:
        """Записывает описание数据集.
        
        Args:
            f: Файловый объект для записи
        """
        f.write("DATASET STRUCTURED_POINTS\n")
        
        dimensions = self.grid.get_dimensions()
        origin = self.grid.get_origin()
        spacing = self.grid.get_spacing()
        
        f.write(f"DIMENSIONS {dimensions[0]} {dimensions[1]} {dimensions[2]}\n")
        f.write(f"ORIGIN {origin[0]} {origin[1]} {origin[2]}\n")
        f.write(f"SPACING {spacing[0]} {spacing[1]} {spacing[2]}\n")
